stages:
  - develop # develop branch

### develop ###
deploy_dev:
  stage: develop
  only:
    - develop
  before_script:
    - /mc/dvwebinarbatch/shellscript/dvwebinarbatch-startup.sh stop

  script:
    - sleep 10s
    - tar cvf /mc/dvwebinarbatch/dvwebinarbatch-back/dvwebinarbatch$(date +%Y%m%d%H%M%S).tar /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
    - rm -rf /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
    - sleep 2s
    - cp  /mc/jenkins/dvwebinarbatch/dvwebinar-batch.jar /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
    - sleep 5s
    - find  /mc/dvwebinarbatch/data/dvwebinarbatch -exec  touch  {}  \;

  after_script:
    - /mc/dvwebinarbatch/shellscript/dvwebinarbatch-startup.sh start
    - sleep 10s
  tags:
    - developbatch