---
stages:
- build
- develop_deploy

build:
  stage: build
  script:
    - mvn clean package  # Maven을 사용하여 JAR 파일을 빌드합니다
  artifacts:
    paths:
      - target/*.jar  # 빌드된 JAR 파일을 아티팩트로 등록합니다

deploy:
  stage: develop_deploy
  script:
#  - echo "dvwebinar-batch restart start.."정
#  - sleep 1s
#  - "/mc/dvwebinarbatch/shellscript/dvwebinarbatch-startup.sh stop"
#  - sleep 10s
#  - tar cvf /mc/dvwebinarbatch/dvwebinarbatch-back/dvwebinarbatch$(date +%Y%m%d%H%M%S).tar \
#    /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
#  - sleep 3s
#  - rm -rf /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
#  - sleep 2s
#  - cp /mc/jenkins/dvwebinarbatch/target/dvwebinar-batch.jar /mc/dvwebinarbatch/data/dvwebinarbatch/dvwebinar-batch.jar
#  - sleep 5s
#  - find /mc/dvwebinarbatch/data/dvwebinarbatch -exec touch {} \;
#  - sleep 5s
#  - "/mc/dvwebinarbatch/shellscript/dvwebinarbatch-startup.sh start"
#  - sleep 10s
#  - echo "dvwebinar-batch restart finish.."
#  - exit 0
  - /mc/dvwebinarbatch/shellscript/jenkins_run.sh
  tags:
  - developbatch
