stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
  tags:
    - batch-dev
