stages:
  - build
  - deploy

build:
  stage: build
  only:
    - develop
  script:
    - mvn clean install
  after_script:
    - echo 'build success!'
  tags:
    - batch-dev

deploy:
  stage: deploy
  script:
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
    - echo "batch commit and push ..."
  tags:
    - batch-dev
