##### dev 설정 #####
spring.profiles: dev
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://118.67.143.191:3306/dvwebinar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true
    username: dvwebinar
    password: "docdnpqlsk123!@#"
    sql-script-encoding: UTF-8
    dbcp2:
      initial-size: 4
      max-idle: 8
      min-idle: 4
    tomcat:
      initial-size: 4
      max-active: 10
      max-idle: 8
      min-idle: 4
  jpa:
    database: mysql
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

server:
  port: 9107
  ajp:
    enable: true
    port: 9108

logging:
  file: /log/dvwebinar/logs/batch/logback
  level:
    org.springframework:
      core: info
      beans: info
      context: info
      web: info

    com.mcircle.webinar: info

    org.hibernate.type.descriptor.sql: info


webinar.context: http://dev.dvwebinar.co.kr:9105