##### real 설정 #####
spring.profiles: real
spring:
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:replication://175.106.97.180:3306,175.106.99.106:3306/dvwebinar?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true
    username: dvwebinar
    password: "docdnpqlsk123!@#"
    sql-script-encoding: UTF-8
    tomcat:
      initial-size: 4
      max-active: 10
      max-idle: 8
      min-idle: 4
  jpa:
    database: mysql
    hibernate.ddl-auto: none    ##### 절대 수정 금지 #####
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

server:
  port: 9107
  ajp:
    enable: true
    port: 9108

logging:
  file: /log/dvwebinar/logs/batch/logback
  level:
    org.springframework:
      core: info
      beans: info
      context: info
      web: info

    com.mcircle.webinar: info

    org.hibernate.type.descriptor.sql: info